##### Imports

In [9]:
import sys
import pandas as pd
import requests
import comtradeapicall
from datetime import date
from datetime import timedelta

### UNComtrade API Usage Examples

UN Comtrade has 3 main API tiers: 
 - Public
 - Free Subscription
 - Paid Subscription

In [3]:
# Set some variables
today = date.today()
yesterday = today - timedelta(days=1)
lastweek = today - timedelta(days=7)
subscription_key = open("../uncomtrade_api_key.txt").read().strip()

Available resources

In [4]:
comtradeapicall.listReference()

,category,variable,description,fileuri
0,dataitem,Trade data items,List of data items/variables used in UN Comtrade,https://comtradeapi.un.org/files/v1/app/refere...
1,freq,Frequency,The time interval at which observations occur,https://comtradeapi.un.org/files/v1/app/refere...
2,flow,Trade Flow,"Trade flow or sub-flow (exports, re-exports, i...",https://comtradeapi.un.org/files/v1/app/refere...
3,mot,Mode of Transports,The mode of transport used when goods enter or...,https://comtradeapi.un.org/files/v1/app/refere...
4,partner,Partner country/area,The partner country or geographic area for the...,https://comtradeapi.un.org/files/v1/app/refere...
5,reporter,Reporter,The country or geographic area to which the me...,https://comtradeapi.un.org/files/v1/app/refere...
6,qtyunit,Units of quantity,The unit for quantity and alternate quantity d...,https://comtradeapi.un.org/files/v1/app/refere...
7,mos,Mode of Supply,The mode of supply on delivery of services (tr...,https://comtradeapi.un.org/files/v1/app/refere...
8,customs,Customs Procedure Code,Customs or statistical procedure,https://comtradeapi.un.org/files/v1/app/refere...
9,cmd:B4,Product [BEC Rev. 4],The classification of BEC Rev.4 – goods and se...,https://comtradeapi.un.org/files/v1/app/refere...
10,cmd:B5,Product [BEC Rev. 5],The classification of BEC Rev.5 – goods or ser...,https://comtradeapi.un.org/files/v1/app/refere...
11,cmd:EB02,Product [EBOPS 2002],The classification of EBOPS 2002 – services,https://comtradeapi.un.org/files/v1/app/refere...
12,cmd:EB10,Product [EBOPS 2010],The classification of EBOPS 2010 – services,https://comtradeapi.un.org/files/v1/app/refere...
13,cmd:EB10S,Product [EBOPS 2010 SDMX],The classification of EBOPS 2010 SDMX – services,https://comtradeapi.un.org/files/v1/app/refere...
14,cmd:EB,Product [EBOPS],The classification of Combined EBOPS – services,https://comtradeapi.un.org/files/v1/app/refere...
15,cmd:H0,Product [HS 1992],The classification of HS 1992 – goods,https://comtradeapi.un.org/files/v1/app/refere...
16,cmd:H1,Product [HS 1996],The classification of HS 1996 – goods,https://comtradeapi.un.org/files/v1/app/refere...
17,cmd:H2,Product [HS 2002],The classification of HS 2002 – goods,https://comtradeapi.un.org/files/v1/app/refere...
18,cmd:H3,Product [HS 2007],The classification of HS 2007 – goods,https://comtradeapi.un.org/files/v1/app/refere...
19,cmd:H4,Product [HS 2012],The classification of HS 2012 – goods,https://comtradeapi.un.org/files/v1/app/refere...
20,cmd:H5,Product [HS 2017],The classification of HS 2017 – goods,https://comtradeapi.un.org/files/v1/app/refere...
21,cmd:H6,Product [HS 2022],The classification of HS 2022 – goods,https://comtradeapi.un.org/files/v1/app/refere...
22,cmd:HS,Product [HS],The classification of Combined HS – goods,https://comtradeapi.un.org/files/v1/app/refere...
23,cmd:S1,Product [SITC Rev.1],The classification of SITC Rev.1 – goods,https://comtradeapi.un.org/files/v1/app/refere...
24,cmd:S2,Product [SITC Rev.2],The classification of SITC Rev.2 – goods,https://comtradeapi.un.org/files/v1/app/refere...
25,cmd:S3,Product [SITC Rev.3],The classification of SITC Rev.3 – goods,https://comtradeapi.un.org/files/v1/app/refere...
26,cmd:S4,Product [SITC Rev.4],The classification of SITC Rev.4 – goods,https://comtradeapi.un.org/files/v1/app/refere...
27,cmd:SS,Product [SITC],The classification of Combined SITC – goods,https://comtradeapi.un.org/files/v1/app/refere...
28,ais:dataitems,AIS Data Items,Data items used in experimental seaborne trade...,https://comtradeapi.un.org/files/v1/app/refere...
29,ais:countriesareas,AIS Countries/Areas,Countries and Areas used in experimental seabo...,https://comtradeapi.un.org/files/v1/app/refere...
30,ais:flows,AIS Trade Flow,Trade flows used in experimental seaborne trad...,https://comtradeapi.un.org/files/v1/app/refere...
31,ais:vesseltypes,AIS Vessel Types,Vessel types used in experimental seaborne tra...,https://comtradeapi.un.org/files/v1/app/refere...

## TariffLine Data

In [5]:
# Call without Subscription
df = comtradeapicall.previewTarifflineData(typeCode='C', freqCode='A', clCode='HS', period='2023',
                                             reporterCode='32', cmdCode='0', flowCode='M', partnerCode=76, partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=5000, format_output='JSON',
                                             countOnly=None, includeDesc=True)

Check latest update

In [6]:
comtradeapicall.getLiveUpdate(subscription_key=subscription_key)

,size,startedAt,completedAt,status,lastUpdated,queuedAt,releaseStatus,reporterCode,freqCode,typeCode,classificationCode,period
0,158115368,2025-04-15 02:32:15Z,2025-04-15 02:25:46Z,Success,"Tuesday, April 15, 2025","Tuesday, April 15, 2025 4:25:45 AM",Released,70,M,C,H6,202411
1,163455529,2025-04-15 01:20:33Z,2025-04-15 01:13:55Z,Success,"Tuesday, April 15, 2025","Tuesday, April 15, 2025 3:13:45 AM",Released,70,M,C,H6,202410
2,161226666,2025-04-15 01:05:44Z,2025-04-15 00:58:13Z,Success,"Tuesday, April 15, 2025","Tuesday, April 15, 2025 2:57:29 AM",Released,70,M,C,H6,202407
3,155888935,2025-04-15 00:45:11Z,2025-04-15 00:38:37Z,Success,"Tuesday, April 15, 2025","Tuesday, April 15, 2025 2:38:04 AM",Released,70,M,C,H6,202409
4,155299147,2025-04-15 00:32:10Z,2025-04-15 00:22:53Z,Success,"Tuesday, April 15, 2025","Tuesday, April 15, 2025 2:22:26 AM",Released,70,M,C,H6,202406
5,155033329,2025-04-14 23:58:55Z,2025-04-14 23:48:35Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 1:47:42 AM",Released,70,M,C,H6,202405
6,148890726,2025-04-14 23:57:17Z,2025-04-14 23:50:09Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 1:49:30 AM",Released,70,M,C,H6,202408
7,161508941,2025-04-14 23:23:37Z,2025-04-14 23:12:49Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 1:12:39 AM",Released,70,M,C,H6,202403
8,160103549,2025-04-14 23:21:43Z,2025-04-14 23:12:25Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 1:12:14 AM",Released,70,M,C,H6,202404
9,156658102,2025-04-14 22:49:17Z,2025-04-14 22:38:55Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 12:38:22 AM",Released,70,M,C,H6,202402
10,139437072,2025-04-14 22:42:37Z,2025-04-14 22:33:15Z,Success,"Monday, April 14, 2025","Tuesday, April 15, 2025 12:33:04 AM",Released,70,M,C,H6,202401
11,32918533,2025-04-14 20:20:34Z,2025-04-14 20:18:14Z,Success,"Monday, April 14, 2025","Monday, April 14, 2025 10:17:35 PM",Released,344,A,C,H6,2024
12,28183875,2025-04-14 20:19:14Z,2025-04-14 20:16:26Z,Success,"Monday, April 14, 2025","Monday, April 14, 2025 10:16:09 PM",Released,344,A,C,S4,2024
13,3452114,2025-04-14 20:18:14Z,2025-04-14 20:17:19Z,Success,"Monday, April 14, 2025","Monday, April 14, 2025 10:17:06 PM",Released,344,A,C,B5,2024
14,892926,2025-04-14 20:12:12Z,2025-04-14 20:11:50Z,Success,"Monday, April 14, 2025","Monday, April 14, 2025 10:11:26 PM",Released,344,A,C,B4,2024
15,156857376,2025-04-13 05:25:25Z,2025-04-13 05:22:44Z,Success,"Sunday, April 13, 2025","Sunday, April 13, 2025 7:21:53 AM",Released,70,M,C,H6,202412
16,30278787,2025-04-12 22:26:48Z,2025-04-12 22:20:17Z,Success,"Saturday, April 12, 2025","Sunday, April 13, 2025 12:20:17 AM",Released,97,A,C,B5,2024
17,8287511,2025-04-12 21:38:06Z,2025-04-12 21:35:54Z,Success,"Saturday, April 12, 2025","Saturday, April 12, 2025 11:35:13 PM",Released,97,A,C,B4,2024
18,121217,2025-04-11 21:58:42Z,2025-04-11 21:58:32Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:31 PM",Released,60,A,C,B4,1997
19,398113,2025-04-11 21:58:41Z,2025-04-11 21:58:30Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:27 PM",Released,52,A,C,B4,1997
20,375547,2025-04-11 21:58:24Z,2025-04-11 21:58:22Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:20 PM",Released,50,A,C,B4,1997
21,192189,2025-04-11 21:58:22Z,2025-04-11 21:58:13Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:10 PM",Released,44,A,C,B4,1997
22,191428,2025-04-11 21:58:18Z,2025-04-11 21:58:17Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:15 PM",Released,84,A,C,B4,1997
23,203232,2025-04-11 21:58:08Z,2025-04-11 21:58:06Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:58:04 PM",Released,31,A,C,B4,1997
24,222489,2025-04-11 21:58:06Z,2025-04-11 21:57:59Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:59 PM",Released,96,A,C,B4,1997
25,119248,2025-04-11 21:57:58Z,2025-04-11 21:57:57Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:53 PM",Released,108,A,C,B4,1997
26,182748,2025-04-11 21:57:52Z,2025-04-11 21:57:47Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:47 PM",Released,132,A,C,B4,1997
27,290694,2025-04-11 21:57:50Z,2025-04-11 21:57:46Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:42 PM",Released,120,A,C,B4,1997
28,105202,2025-04-11 21:57:40Z,2025-04-11 21:57:39Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:38 PM",Released,140,A,C,B4,1997
29,82061,2025-04-11 21:57:37Z,2025-04-11 21:57:36Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:33 PM",Released,174,A,C,B4,1997
30,382159,2025-04-11 21:57:36Z,2025-04-11 21:57:29Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:29 PM",Released,188,A,C,B4,1997
31,199235,2025-04-11 21:57:25Z,2025-04-11 21:57:20Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:16 PM",Released,234,A,C,B4,1997
32,178917,2025-04-11 21:57:25Z,2025-04-11 21:57:24Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:22 PM",Released,212,A,C,B4,1997
33,258514,2025-04-11 21:57:17Z,2025-04-11 21:57:12Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:12 PM",Released,231,A,C,B4,1997
34,256375,2025-04-11 21:57:12Z,2025-04-11 21:57:08Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:07 PM",Released,222,A,C,B4,1997
35,218761,2025-04-11 21:57:11Z,2025-04-11 21:57:04Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:57:03 PM",Released,270,A,C,B4,1997
36,229915,2025-04-11 21:57:03Z,2025-04-11 21:57:00Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:58 PM",Released,268,A,C,B4,1997
37,115736,2025-04-11 21:56:55Z,2025-04-11 21:56:54Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:53 PM",Released,214,A,C,B4,1997
38,426348,2025-04-11 21:56:53Z,2025-04-11 21:56:51Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:48 PM",Released,288,A,C,B4,1997
39,68549,2025-04-11 21:56:45Z,2025-04-11 21:56:44Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:43 PM",Released,296,A,C,B4,1997
40,138730,2025-04-11 21:56:41Z,2025-04-11 21:56:40Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:40 PM",Released,304,A,C,B4,1997
41,206807,2025-04-11 21:56:38Z,2025-04-11 21:56:37Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:36 PM",Released,308,A,C,B4,1997
42,311002,2025-04-11 21:56:37Z,2025-04-11 21:56:33Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:31 PM",Released,320,A,C,B4,1997
43,220003,2025-04-11 21:56:37Z,2025-04-11 21:56:29Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:27 PM",Released,328,A,C,B4,1997
44,278989,2025-04-11 21:56:26Z,2025-04-11 21:56:25Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:23 PM",Released,324,A,C,B4,1997
45,246623,2025-04-11 21:56:25Z,2025-04-11 21:56:21Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:17 PM",Released,340,A,C,B4,1997
46,414508,2025-04-11 21:56:24Z,2025-04-11 21:56:14Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:13 PM",Released,364,A,C,B4,1997
47,436481,2025-04-11 21:56:11Z,2025-04-11 21:56:09Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:09 PM",Released,384,A,C,B4,1997
48,600492,2025-04-11 21:56:09Z,2025-04-11 21:55:49Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:55:47 PM",Released,422,A,C,B4,1997
49,365405,2025-04-11 21:56:09Z,2025-04-11 21:56:05Z,Success,"Friday, April 11, 2025","Friday, April 11, 2025 11:56:05 PM",Released,388,A,C,B4,1997

### Reporters (Countries)

In [13]:
reporters = pd.read_csv("../../data/UNComtrade/reporters.csv")
reporters_ids = list(reporters.id)
reporters_ids = ",".join(list(map(str,reporters_ids)))
len(reporters_ids)

989

Get some specific data as a test:
- Type = C (Commodities)
- Frequency = A (Annual)
- HS Nomenclature
- Year = 2022
- Reporter = 76 (Brazil)
- Commodity = 10 (Cereals)
- Flow = X (Exports)
- Partner = All partners

In [28]:
brazil_cereals_X = comtradeapicall.getTarifflineData(subscription_key=subscription_key, typeCode='C', freqCode='A', clCode='HS', period='2022',
                                             reporterCode='76', cmdCode='10', flowCode='X', partnerCode=reporters_ids, partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=None, format_output='JSON', 
                                             countOnly=None, includeDesc=True)

In [29]:
brazil_cereals_X.head()

,typeCode,freqCode,refPeriodId,period,reporterCode,reporterDesc,reporterISO,flowCode,flowDesc,partnerCode,...,qtyUnitAbbr,qty,altQtyUnitCode,altQtyUnitAbbr,altQty,netWgt,grossWgt,cifvalue,fobvalue,primaryValue
0,C,A,20220101,2022,76,Brazil,BRA,X,Export,196,...,kg,20.0,8,kg,20.0,20.0,0.0,0.0,6.0,6.0
1,C,A,20220101,2022,76,Brazil,BRA,X,Export,430,...,kg,12.0,8,kg,12.0,12.0,0.0,0.0,61.0,61.0
2,C,A,20220101,2022,76,Brazil,BRA,X,Export,430,...,kg,660.0,8,kg,660.0,660.0,0.0,0.0,588.0,588.0
3,C,A,20220101,2022,76,Brazil,BRA,X,Export,591,...,kg,150.0,8,kg,150.0,150.0,0.0,0.0,468.0,468.0
4,C,A,20220101,2022,76,Brazil,BRA,X,Export,792,...,kg,25.0,8,kg,25.0,25.0,0.0,0.0,81.0,81.0

Let's check Argentina's imports from Brazil in Cereals

In [39]:
argentina_cereals_M = comtradeapicall.previewTarifflineData(typeCode='C', freqCode='A', clCode='HS', period='2022',
                                             reporterCode='32', cmdCode='10', flowCode='M', partnerCode="76", partner2Code=None,
                                             customsCode=None, motCode=None, maxRecords=5000, format_output='JSON', 
                                             countOnly=None, includeDesc=True)

In [40]:
argentina_cereals_M.head()

,typeCode,freqCode,refPeriodId,period,reporterCode,reporterDesc,reporterISO,flowCode,flowDesc,partnerCode,...,qtyUnitAbbr,qty,altQtyUnitCode,altQtyUnitAbbr,altQty,netWgt,grossWgt,cifvalue,fobvalue,primaryValue
0,C,A,20220101,2022,32,Argentina,ARG,M,Import,76,...,kg,0.01,8,kg,0.01,0.01,0.0,0.49,0.26,0.49
1,C,A,20220101,2022,32,Argentina,ARG,M,Import,76,...,kg,77.00,8,kg,77.00,77.00,0.0,896.96,192.50,896.96
2,C,A,20220101,2022,32,Argentina,ARG,M,Import,76,...,kg,35.00,8,kg,35.00,35.00,0.0,489.47,87.50,489.47
3,C,A,20220101,2022,32,Argentina,ARG,M,Import,76,...,kg,20.00,8,kg,20.00,20.00,0.0,335.18,60.00,335.18
4,C,A,20220101,2022,32,Argentina,ARG,M,Import,76,...,kg,7.44,8,kg,7.44,7.44,0.0,941.08,446.40,941.08

See if they match

In [41]:
print(brazil_cereals_X[brazil_cereals_X['partnerCode'] == 32]["primaryValue"].sum())
print(argentina_cereals_M[argentina_cereals_M['partnerCode'] == 76]["primaryValue"].sum())

5510993.0
6227143.600000001

Let's look at the available columns

In [42]:
df[df.cmdCode == "02023000"].columns

Index(['typeCode', 'freqCode', 'refPeriodId', 'period', 'reporterCode',
       'reporterDesc', 'reporterISO', 'flowCode', 'flowDesc', 'partnerCode',
       'partnerDesc', 'partnerISO', 'partner2Code', 'partner2Desc',
       'partner2ISO', 'classificationCode', 'cmdCode', 'cmdDesc',
       'customsCode', 'customsDesc', 'mosCode', 'motCode', 'motDesc',
       'qtyUnitCode', 'qtyUnitAbbr', 'qty', 'altQtyUnitCode', 'altQtyUnitAbbr',
       'altQty', 'netWgt', 'grossWgt', 'cifvalue', 'fobvalue', 'primaryValue'],
      dtype='object')

Let's see what columns are non-redundant

In [44]:
for col in df.columns:
    if len(df[df.cmdCode == "02023000"][col].unique()) > 1:
        print(col)

qty
altQty
netWgt
cifvalue
fobvalue
primaryValue